name: training-env
dependencies:
  - python=3.8
  - pip:
      - mlflow
      - scikit-learn
      - pandas
      - joblib
      - azure-identity       # For Azure authentication (ClientSecretCredential)
      - azure-ai-ml          # For Azure ML SDK to interact with Azure Machine Learning
      - azureml.mlflow
