name: Automated Model Training and Deployment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      LOCATION: ${{ secrets.LOCATION }}
      # Other environment variables will be set from parameters.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # **New Step: Read parameters.json and set environment variables**
      - name: Read parameters.json
        id: read_parameters
        run: |
          KEY_VAULT=$(jq -r '.keyVaultName.value' parameters.json)
          WORKSPACE_NAME=$(jq -r '.mlWorkspaceName.value' parameters.json)
          STORAGE_NAME=$(jq -r '.storageAccountName.value' parameters.json)
          INSIGHTS_NAME=$(jq -r '.applicationInsightsName.value' parameters.json)
          LOCATION=$(jq -r '.location.value' parameters.json)

          echo "AZURE_KEY_VAULT=$KEY_VAULT" >> $GITHUB_ENV
          echo "AZURE_WORKSPACE_NAME=$WORKSPACE_NAME" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT_NAME=$STORAGE_NAME" >> $GITHUB_ENV
          echo "APPLICATION_INSIGHTS_NAME=$INSIGHTS_NAME" >> $GITHUB_ENV
          echo "LOCATION=$LOCATION" >> $GITHUB_ENV
        shell: bash

      - name: Azure Login using OpenID Connect
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Install dependencies
        run: |
          pip install snowflake-connector-python pandas azure-ai-ml snowflake-snowpark-python

      # Retrieve secrets from Azure Key Vault using the name from parameters.json
      - name: Get Secrets from Azure Key Vault
        id: get_secrets
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ env.AZURE_KEY_VAULT }}
          secrets: |
            SNOWFLAKEUSER
            SNOWFLAKEPASSWORD
            SNOWFLAKEACCOUNT
            SNOWFLAKEWAREHOUSE
            SNOWFLAKEDATABASE
            SNOWFLAKESCHEMA
            SNOWFLAKEROLE

      - name: Extract data from Snowflake
        env:
          SNOWFLAKEUSER: ${{ steps.get_secrets.outputs.SNOWFLAKEUSER }}
          SNOWFLAKEPASSWORD: ${{ steps.get_secrets.outputs.SNOWFLAKEPASSWORD }}
          SNOWFLAKEACCOUNT: ${{ steps.get_secrets.outputs.SNOWFLAKEACCOUNT }}
          SNOWFLAKEWAREHOUSE: ${{ steps.get_secrets.outputs.SNOWFLAKEWAREHOUSE }}
          SNOWFLAKEDATABASE: ${{ steps.get_secrets.outputs.SNOWFLAKEDATABASE }}
          SNOWFLAKESCHEMA: ${{ steps.get_secrets.outputs.SNOWFLAKESCHEMA }}
        run: python data_extraction.py

      - name: Run training job on Azure ML
        env:
          AZURE_CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ env.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: ${{ env.AZURE_RESOURCE_GROUP }}
          AZURE_WORKSPACE_NAME: ${{ env.AZURE_WORKSPACE_NAME }}
        run: python run_training_job.py

      - name: Deploy model to Snowflake
        env:
          SNOWFLAKEUSER: ${{ steps.get_secrets.outputs.SNOWFLAKEUSER }}
          SNOWFLAKEPASSWORD: ${{ steps.get_secrets.outputs.SNOWFLAKEPASSWORD }}
          SNOWFLAKEACCOUNT: ${{ steps.get_secrets.outputs.SNOWFLAKEACCOUNT }}
          SNOWFLAKEWAREHOUSE: ${{ steps.get_secrets.outputs.SNOWFLAKEWAREHOUSE }}
          SNOWFLAKEDATABASE: ${{ steps.get_secrets.outputs.SNOWFLAKEDATABASE }}
          SNOWFLAKESCHEMA: ${{ steps.get_secrets.outputs.SNOWFLAKESCHEMA }}
          SNOWFLAKEROLE: ${{ steps.get_secrets.outputs.SNOWFLAKEROLE }}
        run: python deploy_udf.py
