name: Scheduled Job

on: workflow_dispatch

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run your task
        run: echo "Running scheduled job at 11:05 PM Central Time"
