name: Scheduled Job

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '17 5 * * *'

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run your task
        run: echo "Running scheduled job at 11:05 PM Central Time"
