name: Azure Infrastructure Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Resources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./azure_resources.json
          parameters: >
            {
              "location": {
                "value": "eastus"
              },
              "keyVaultName": {
                "value": "mlops-keyvault"
              },
              "mlWorkspaceName": {
                "value": "mlops-workspace"
              },
              "storageAccountName": {
                "value": "mlopsstorage-MLOPS_TEST"
              }
            }

      - name: Assign Roles to Service Principal
        run: |
          az role assignment create --assignee ${{ secrets.AZURE_CREDENTIALS.clientId }} --role "Contributor" --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}

